package dev.affan.teller.domain;

public enum AuditEventType {
    POLICY_CREATED,
    RULE_CREATED,
    DECISION_CREATED,
    APPROVAL_CREATED,
    APPROVAL_APPROVED,
    APPROVAL_DENIED,
    APPROVAL_EXPIRED,
    DLQ_REPLAYED,
    ACCOUNT_CREATED,
    ACCOUNT_DEPOSITED,
    TRANSFER_CREATED,
    TRANSFER_POSTED,
    TRANSFER_HELD,
    TRANSFER_DENIED,
    TRANSFER_REVERSED,
    RECONCILIATION_MISMATCH
}
